### ISSUE TITLE
Plugin does not appear in Audacious 

### ISSUE THREAD

**Issue by JustH3LL** [darktohka/audacious-plugin-rpc#1]
![image](https://user-images.githubusercontent.com/22642619/45600440-b53ce780-b9ca-11e8-95b9-feb054a333f7.png)
![image](https://user-images.githubusercontent.com/22642619/45600448-d43b7980-b9ca-11e8-9e6c-19714114d994.png)

I followed the instructions exactly as stated; tried restarting Audacious several times and rebooting with no luck

**Comment by darktohka** [comment]
Can you please tell me what distribution you are using? Are you on a 32-bit or a 64-bit system? The build in the releases page is built for 64-bit Debian systems, though other distributions that are 64-bit should also work. I assume that you're on 64-bit since you do have the x86_64-linux-gnu lib folder.

Can you run `audacious` in the terminal instead of the global menu? It should give you more information about why the plugin is not being loaded.

Also run `ldd /usr/lib/x86_64-linux-gnu/audacious/General/libaudacious-plugin-rpc.so` and copy the output here. Thank you!

**Comment by JustH3LL** [comment]
64-bit Elementary OS 0.4.1 Loki

```justh3ll@JustH3LL-LT:~$ sudo audacious
[sudo] password for justh3ll:         
ERROR plugin-load.cc:61 [plugin_load]: /usr/lib/x86_64-linux-gnu/audacious/General/libaudacious-plugin-rpc.so could not be loaded: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/audacious/General/libaudacious-plugin-rpc.so)
WARNING pixbufs.cc:132 [audgui_pixbuf_from_data]: While loading pixbuf: Error interpreting JPEG image file (Application transferred too few scanlines)
WARNING pixbufs.cc:132 [audgui_pixbuf_from_data]: While loading pixbuf: Error interpreting JPEG image file (Application transferred too few scanlines)

(audacious:2638): IBUS-WARNING **: The owner of /home/justh3ll/.config/ibus/bus is not root!



```

Evidently, there's a missing dependency known as GLib based off of what I'm looking at. I'm going to attempt to fix the missing dependency and report back on the results 

```justh3ll@JustH3LL-LT:~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
my result when checking for installed GLib versions

**Comment by darktohka** [comment]
Looks like Elementary OS Loki is based on Ubuntu 16.04.2, which means it ships with an outdated libc version.

You'll have to update the libc.so.6 library either by adding Bionic backports or by adding third-party PPAs.

If you don't want to update the libc.so.6, you can follow the compilation steps in this repository's README.md instead, to rebuild the plugin with the older GNU C Library.

I'll be heading to bed now, so I can't respond until I wake up. Hopefully you get somewhere!

**Comment by JustH3LL** [comment]
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test` , an apt update, and some updates in Elementary's AppCenter fixed my issue with GLib being out of date
```justh3ll@JustH3LL-LT:~$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
justh3ll@JustH3LL-LT:~$ 
```

Now I'm getting this error:
```justh3ll@JustH3LL-LT:~$ audacious
ERROR plugin-load.cc:79 [plugin_load]: /usr/lib/x86_64-linux-gnu/audacious/General/libaudacious-plugin-rpc.so is not compatible with this version of Audacious.
Gtk-Message: Failed to load module "pantheon-filechooser-module"
WARNING pixbufs.cc:132 [audgui_pixbuf_from_data]: While loading pixbuf: Error interpreting JPEG image file (Application transferred too few scanlines)
WARNING pixbufs.cc:132 [audgui_pixbuf_from_data]: While loading pixbuf: Error interpreting JPEG image file (Application transferred too few scanlines)
justh3ll@JustH3LL-LT:~$ 
```
Which I'm assuming is meaning Audacious is out of date, which I'm going to get to working on


Have a good sleep!

Edit: Checking between my install of Audacious and the latest on https://audacious-media-player.org/ , I'm three years behind!

Edit2: Managed to update Audacious and everything is functioning now!
