### ISSUE TITLE
Audacious crashes when changing songs

### ISSUE THREAD

**Issue by SameytheHedgehog** [darktohka/audacious-plugin-rpc#3]
while I have this plugin activated, Audacious crashes every so often, and when running it through the terminal this is the error that it prints out while crashing.

without the plugin, Audacious works perfectly fine.
https://i.imgur.com/6fwnfWU.png

**Comment by SameytheHedgehog** [comment]
Actually, its been a while and I believe this was because I had an outdated release of Audacious. I haven't had this issue with the latest release of Audacious.

**Comment by darktohka** [comment]
This was fixed in https://github.com/darktohka/audacious-plugin-rpc/commit/b459439e20e54e0971d186adeebcd8012e529d20 but you do have to compile the plugin from scratch.
